# Generated by Django 3.2.3 on 2021-05-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='user',
            new_name='like_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
